### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by IvoCloud** [guyfrancoeur/CTQ-UX#1]
Bonjour,

Est-ce qu'on garde les Modals ou on utilise des href vers login, new user, forgot password ?
J'ai commence les modals pour create user, est-ce que je les continue ?

Ce que je peux faire c'est de finir les html avec les modals et faire un jQuerry load html pour les ensuite attacher dans les index.html , l.html etc ? 

Un peu comme des templates.

Ou sinon, au lieu des modals, je peux faire un ajax qui transforme la page de Login à 'Mot de passe oublié' ou 'S'inscrire'

Merci

**Comment by guyfrancoeur** [comment]
Bonjour,

Les formes modales c'est idéale pour plusieurs écrans.

Pour ajouter ou editer c'est plus simple.

> Ce que je peux faire c'est de finir les html avec les modals et faire un jQuerry load html pour les ensuite attacher dans les index.html , l.html etc ?

Oui biensur.

Merci.
